config/routes.rb
      get "/patchManagement/server/serverCentric", to: "servers#serverCentric"
    end
  end

  scope path: '/api/v1', defaults: {format: 'json'}, as: :api do
    scope :module => 'api/v1/um', constraints: SGTools::Rails::REST.api_constraints_class.new(version: 1, default: true)  do

      match '/scheduledEntries', to: 'update_managers#scheduledEntries', via: [:get, :post]
      put '/scheduledEntries/:id', to: 'update_managers#scheduledEntries'

      match '/latestGoldPolicy', to: 'update_managers#latestGoldPolicy', via: [:get]
      
      match '/goldPolicies', to: 'update_managers#goldPolicies', via: [:get, :post]
      get '/goldPolicies/:id', to: 'update_managers#goldPolicies'

      get '/patches/:id', to: 'update_managers#patches'
      post '/patches', to: 'update_managers#patches'

      post '/tickets', to: 'update_managers#tickets'
      get  '/tickets/:id', to: 'update_managers#ticket'
      get '/tickets/comments/:id', to: 'update_managers#tickets_comments'
      put '/tickets/comments/:id', to: 'update_managers#update_comment'

      get '/servers', to: 'update_managers#servers'
    end
  end

  scope path: '/', defaults: {format: 'json'}, as: :api do
    scope :module => 'api/v1/dns_ipam' , constraints: SGTools::Rails::REST.api_constraints_class.new(version: 1, default: true) do
      resources :dns_audits, only: [:create, :index]
      get 'allrecords', to: 'infoblox#get_dns_ipam'
      get 'record:cname', to: 'infoblox#get_dns_ipam'
      get 'nsgroup', to: 'infoblox#get_dns_ipam'
      get 'zone_auth', to: 'infoblox#get_dns_ipam'
      get 'company_zones', to: 'infoblox#get_zone_auth'
      get 'record:a', to: 'infoblox#get_dns_ipam'
      get 'record:aaaa', to: 'infoblox#get_dns_ipam'
      get 'record:cname', to: 'infoblox#get_dns_ipam'
      get 'record:ptr', to: 'infoblox#get_dns_ipam'
      get 'record:mx', to: 'infoblox#get_dns_ipam'
      get 'record:srv', to: 'infoblox#get_dns_ipam'
      get 'record:naptr', to: 'infoblox#get_dns_ipam'
      get 'record:txt', to: 'infoblox#get_dns_ipam'
      get 'ip_subnet_list/WHERE/:query', to: 'infoblox#get_ip_list', constraints: { query: /[^\/]+/ }
      get 'ip6_subnet6_list/WHERE/:query', to: 'infoblox#get_ip_list', constraints: { query: /[^\/]+/ }

      post 'zone_auth', to: 'infoblox#post_dns_ipam'
      post 'record:a', to: 'infoblox#post_dns_ipam'
      post 'record:aaaa', to: 'infoblox#post_dns_ipam'
      post 'record:cname', to: 'infoblox#post_dns_ipam'
      post 'record:ptr', to: 'infoblox#post_dns_ipam'
      post 'record:mx', to: 'infoblox#post_dns_ipam'
      post 'record:srv', to: 'infoblox#post_dns_ipam'
      post 'record:naptr', to: 'infoblox#post_dns_ipam'
      post 'record:txt', to: 'infoblox#post_dns_ipam'

      put 'record:a/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }
      put 'record:cname/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }
      put 'record:aaaa/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }
      put 'record:mx/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }
      put 'record:srv/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }
      put 'record:naptr/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }
      put 'record:txt/:ref/default', to: 'infoblox#put_dns_ipam', constraints: { ref: /[^\/]+/ }

      delete 'record:a/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:cname/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:aaaa/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:ptr/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:mx/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:srv/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:naptr/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      delete 'record:txt/:ref/default', to: 'infoblox#delete_dns_ipam', constraints: { ref: /[^\/]+/ }
      # ipam endpoints
      get '/ipam/getCollection', to: 'ipam#get_collection_by_name'
      get '/ipam/getCollection/:id', to: 'ipam#get_collection_by_id', constraints: {id: /[^\/]+/}
      get '/ipam/getCollection/getAllDocuments', to: 'ipam#get_all_documents'
      get '/ipam/getCollection/getDocOnFieldValue', to: 'ipam#get_wildcard_values'
      get '/ipam/exists/collection', to: 'ipam#check_collection_exists'
      get '/ipam/exists/collection/field', to: 'ipam#check_field_exists'
      get '/ipam/exists/collection/field/Transics', to: 'ipam#check_value_exists'
      get '/ipam/getCollection/count', to: "ipam#get_collection_count"
      get '/ipam/getCollection/getDocOnFieldValue', to: "ipam#get_doc_field"

      post '/ipam/addDocuments', to: 'ipam#add_document'
      put '/ipam/updateDocuments', to: 'ipam#update_document'
      delete '/ipam/deleteDocument', to: 'ipam#delete_document'
    end
  end


  namespace :sungard do
    resources :welcome, :helps, :api_keys, :statements, :menus, :roles, :event_subscriptions, :compliance, :compliance_compute, :companies, :ehealth_companies, :parent_child
   
    match 'status' => 'status#index'
    match 'login_count' => 'status#login_count'
    match 'echo' => 'status#echo'
    match 'acl' => 'status#acl'
    root :to => 'welcome#index'
  end

  namespace :tools do
    get 'service_now', to: 'service_now#index'
    get 'knowledge_base', to: 'knowledge_base#index'
    get 'ids', to: 'ids#index'
    get 'netids', to: 'net_ids#index'
    get 'seim', to: 'seim#index'
    # get 'test', to: 'test#index'
  end

  resources :devices do
    collection do
      get '/core_devices' => 'devices#core_devices'
      get "/:id" => "devices#show"
      get '/device_details/:global_id' => "devices#device_details"
      # itsm widget routes
      get '/:device_id/widgets/device_time'   => 'widgets#device_time', constraints: {device_id: /[^\/]+/}
    end
  end

  resources :sessions
  scope 'graphs/:graph_id' do
    resources :oder,
      :as         => 'graph_order',
      :controller => 'graphs_order',
      :only       => [:create]
  end

  get 'export/devices' => 'export#devices'
  get 'export/interfaces' => 'export#interfaces#export'
  get 'export/events' => 'export#events'
  get 'export/live_events' => 'export#live_events'

  get 'home' => 'welcome#index'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'unmasquerade', to: 'masquerades#destroy', as: 'unmasquerade'
  get 'home_company', to: 'company_masquerades#destroy', as: 'home_company'

  # static pages
  get 'privacy' => 'say#privacy'
  get 'services_data' => 'say#services_data'
  get 'terms' => 'say#terms'
  get 'safe_harbor' => 'say#safe_harbor'
  
  match 'welcome' => 'welcome#landing_page'
  match "/pyxie" => ViewpointPyxieServer, :anchor => false
  match 'update_company_status' => 'companies#update', via: [:post]

  namespace :admin do
    resources :welcome
    resources :sessions, :only => [:create,:new ] unless Rails.env == 'production'
    resources :user_password_resets, :only => [:create]
    resources :user_password_resets, :only => [:create]
    resources :users do
      member do
        get 'change_password'
        put "update_password"
        put "resend_confirmation"
        put 'toggle_unlock'
        put 'toggle_active'
        get 'change_email'
        get 'change_email_success'
        put "update_email"
        get 'convert'
        get 'convert_non_portal'
        get 'cleanup'
      end
    end
    root :to => 'welcome#index'
  end

  namespace :services do
    resources :confirmations
    resources :password_resets
    resources :email_resets
  end

  get "/rs_user_guide" => "application#rs_user_guide", :as => "raas_user_guide"
  get "/user_guide" => "application#user_guide", :as => "viewpoint_user_guide"
  get "/user_guide_allstream" => "application#user_guide_allstream", :as => "viewpoint_user_guide_allstream"
  get "/user_guide_omi" => "application#user_guide_omi", :as => "viewpoint_user_guide_omi"
  get "/tutorials/customer_catalog" => "application#customer_catalog"
  get "/tutorials/remote_intelligent_hands" => "application#remote_intelligent_hands"
  get "/tutorials/secure_site_access" => "application#secure_site_access"
  get "/tutorials/create_ticket" => "application#create_ticket"
  get "/tutorials/ticket_updates" => "application#ticket_updates"
  get "/tutorials/modify_authorizations" => "application#modify_authorizations"
  get "/tutorials/creating_reports" => "application#creating_reports"
  get "/tutorials/notification_matrix" => "application#notification_matrix"
  get "/tutorials/providers_list" => "application#providers_list"
  get "/tutorials/mx_window" => "application#mx_window"
  get "/tutorials/contract_management" => "application#contract_management"
  get "/tutorials/self_service_guide" => "application#self_service_guide"
  
  #Mobile Tutorials 
  get "/tutorials/mobile_guide/:name" => "application#mobile_guides"

  #Video Tutorials
  get "/tutorials/video_guide/:name" => "application#video_guides"

  resources :firewalls,:only => [:index], path: '/firewalls'

  # get "/logs/firewalls", to: "firewalls#index"
  # get "/beta/groups", to: "groups#beta_groups"

  namespace "beta" do
    resources :devices
    resources :interfaces
  end

  # 2f is essential for tw0-factor authentication
  match "/2f/auth", to: "auths#index"

  root :to => 'welcome#index'

  match "/managedservice", :to => "welcome#index"

  match "/401", to: "errors#unauthorized"

app/controllers/sungard/api_keys_controller.rb
class Sungard::ApiKeysController <  VpAdminController

  def index
    @api_keys = ApiKey.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @api_key = ApiKey.new
  end

  def create
    @api_key = ApiKey.new(params[:api_key])
    if @api_key.save
      redirect_to sungard_api_keys_url, :notice => "Created"
    else
      render "new"
    end
  end

  def edit
    @api_key = ApiKey.find(params[:id])
  end

  def update
    @api_key = ApiKey.find(params[:id])
    respond_to do |format|
      if @api_key.update_attributes(params[:api_key])
        format.html { redirect_to [:sungard, @api_key], notice: 'API Key was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def show
    @api_key = ApiKey.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def destroy
    @api_key = ApiKey.find(params[:id])
    @api_key.destroy
    respond_to do |format|
      format.html { redirect_to sungard_api_keys_url }
    end
  end
end

app/controllers/sungard/companies_controller.rb
class Sungard::CompaniesController <  VpAdminController

  before_filter lambda { help_menu_name('masquerade') }  

  def index
    @body_class = "masquerades index single-column"
    @toolname = ': Company Management'
    @errors = []
    @companies = []
    if (can_masquerade? || session[:masq] = "true")
      if params[:search].blank?
        @companies = Company.all(:limit => 50, :deleted_at => nil )
      else
        @companies = Company.search_by_name(params[:search])
      end
    else
      @errors << "should not be allowed to masquerade."
    end
  end

  def show
    @body_class = "single-column"
    @company = Company.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end


  def edit
    @body_class = "single-column"
    @company = Company.find(params[:id])
  end

  def new
    @body_class = "single-column"
    @company = Company.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # companies should not be created from the UI
  def create
  end

  def update
    @body_class = "single-column"
    @company = Company.find(params[:id])
    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html {
          flash[:notice] = 'Company was successfully updated.'
          render :edit
        }
      else
        format.html {
          flash[:notice] = 'Company was successfully updated, not.'
          render :edit
        }
      end
    end
  end

  def destroy
    @company = Company.find_by_guid(params[:id])
    if @company
      @users = User.where(:company_guid => params[:id])
      unless @users.blank?
        begin
          res = MyOpenid.delete_company(params[:id])
        rescue  Net::HTTPError => e 
          logger.error("ERROR: #{e.message}\n" + e.backtrace.join("\n"))
        end
      end
      # This is soft delete we are updating deleted_at with Time.now
      Company.destroy_all(:guid => params[:id] )
      redirect_to sungard_companies_path, :notice => "Company was successfully updated."
    else
      redirect_to sungard_companies_path, :notice => "Company was successfully updated, not."
    end

  end
  #    
  

  private 

  def can_masquerade?
    if @masquerade and @masquerade_user
      @masquerade_user.can_masquerade?
    else
      current_user.can_masquerade?
    end
  end
end

app/controllers/sungard/event_subscriptions_controller.rb
class Sungard::EventSubscriptionsController <  VpAdminController
  def index
    @event_subscriptions = EventSubscription.all_events    
  end 
  
  def show
    @event_subscription = EventSubscription.load_event_subscription(params[:id])
    respond_to do |format|      
      format.html
    end
  end
end

app/controllers/sungard/helps_controller.rb
class Sungard::HelpsController <  VpAdminController
  load_and_authorize_resource
  before_filter :load_instance, :only => [:show, :edit,:update, :destroy]

  def index
    @helps = Help.all
    @toolname = ': Help Management'
    @body_class = "single-column"
  end 
  
  def show
    @body_class = "single-column"
    respond_to do |format|
      format.html # show.html.erb
      @toolname = ': Help Management'
    end
  end

  def new
    @help = Help.new()    
    @toolname = ': new help'
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @toolname = ': edit help'
    @body_class = "single-column"
  end  

  def create    
    @help = Help.new(params[:help])    
    @toolname = ': new help'
    respond_to do |format|
      if @help.save
        format.html { redirect_to [:sungard, @help], notice: 'help was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @toolname = ': edit help'
    respond_to do |format|
      if @help.update_attributes(params[:help])
        format.html { redirect_to [:sungard, @help], notice: 'Help was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @toolname = ': delete help'
  	@help.destroy    
    respond_to do |format|
      format.html { redirect_to sungard_helps_url }
    end    
  end

  private 
  def load_instance
    begin
      @help = Help.find(params[:id]) 
      if @help.blank?
        Rails.logger.info("Unable to load Help with id  #{params[:id]}")
        render 'errors/not_found',  :status => :not_found
      end
    rescue
      Rails.logger.info("Unable to load Help with id  #{params[:id]}")
      render 'errors/not_found',  :status => :not_found
    end
  end

end

app/controllers/sungard/menus_controller.rb
class Sungard::MenusController <  VpAdminController
  load_and_authorize_resource
  before_filter :load_instance, :only => [:show, :edit,:update, :destroy]

  def index
    @menus = Menu.all
    @toolname = ': Menu Management'
  end 
  
  def show
    @toolname = ': Menu Management'
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @menu = Menu.new()    
    @toolname = ': new menu'
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
   @toolname = ': edit menu'
  end  

  def create 
    @toolname = ': new menu'   
    @menu = Menu.new(params[:menu])    
    respond_to do |format|
      if @menu.save
        format.html { redirect_to [:sungard, @menu], notice: 'menu item was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @toolname = ': edit menu'
    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to [:sungard, @menu], notice: 'Menu was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @menu.destroy
        format.html { redirect_to sungard_menus_url }
      else
        format.html { redirect_to sungard_menus_url, notice: 'Unable to delete group as it may be referenced in help management' }
      end
    end    
  end

  private 
  def load_instance
    begin
      @menu = Menu.find(params[:id]) 
      if @menu.blank?
       Rails.logger.info("Unable to load menu with id  #{params[:id]}")
       render 'errors/not_found',  :status => :not_found
      end
    rescue
      Rails.logger.info("Unable to load Menu with id  #{params[:id]}")
      render 'errors/not_found',  :status => :not_found
    end
  end

end

app/views/sungard/compliance_compute/_form.html.erb
<div id="admin_form">  
  <%= form_for @compliance_compute, as: :compliance_compute, url: "/sungard/compliance_compute" do |f| %>
    <table>
       <% if @compliance_compute.errors.any? %>
      <tr>
        <td colspan="100">
          <div class="error_messages">
            <div class="errors">
              <ul>
                <% for message in @compliance_compute.errors.full_messages %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
      <% else %>
        <% if flash[:notice] %>
            <div class="error_messages"><p><%= flash[:notice] %></p></div>
        <% end %>
          </td>
        </tr>
      <% end %>
        <tr>
          <td>
            <%= f.label 'Name*' %>
            <%= f.text_field :name, placeholder: "Parent report name(product)" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.label 'Group Name1*' %>
            <%= f.text_field :group_name1, placeholder: "Child report name(platform).The name must be same as HPNA device group name" %>
          </td>    
        </tr>
        <tr>
          <td>
            <%= f.label 'vCenter Version' %>
            <%= f.text_field :vCenter_Version, placeholder: "Please enter vCenter Version" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.label 'Group Name2*' %>
            <%= f.text_field :group_name2, placeholder: "Child report name(platform).The name must be same as HPNA device group name" %>
          </td>    
        </tr>
        <tr>
          <td>
            <%= f.label 'Esxi Version' %>
            <%= f.text_field :Esxi_Version, placeholder: "Please enter Esxi Version" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.submit 'Create Compliance Group'%>
          </td>
        </tr>
    </table>
  <% end %>
</div>

app/views/sungard/compliance_compute/_tools.html.erb
<% content_for :tools_name, "Compliance Compute Management" %>
<%= render "sungard/shared/tools" %>
<h2 style="display: block;overflow: hidden;line-height: inherit;"><%= @toolname %></h2>
<% if current_user.vp_admin_role? %>
  <%= link_to 'add group', new_sungard_compliance_compute_path, :class => 'add button' %>
<% end %>
<a class="button" onclick="window.history.back()">back</a>

app/views/sungard/compliance_compute/index.html.erb
<% @requirejs_options = {
  'config' => {
    'application' => {
      'disableRouter' => true
    }
  }
}
%>
<% content_for :requirejs do %>

  require(['application'], function(app){
  })

<% end %>
<% unless flash[:notice].blank? %>    
  <div class="error_messages"><p><%= flash[:notice].html_safe %></p></div>
<% end %>
<table class="grid">
  <thead>
    <tr>
      <td></td>
      <td>Name</td>
      <td>Group Name</td>
      <td>Version Number</td>
      <td>Compliant Count</td>
      <td>Non Compliant Count</td>
      <td>Total</td>
      <td></td>
      <td></td>
      <td>Update At</td>
    </tr>
  </thead>
  <tbody>
  <%@compliance_groups.each do |obj| %>
      <tr>
          <td class="delete" style="width: 1%;">
              <% if current_user.vp_admin_role? %>
                  <%= button_to '&times;'.html_safe, [:sungard, obj], :class =>"text-only", :method => "delete", form: { :onsubmit => "return confirm('Are you sure you want to delete this compliance group?')"} %>
              <% end %>  
          </td>
      
      <%= form_for [:sungard,obj] do |f| %>
           
          <td><%= obj.name %></td>
          <td><p><%= obj.group_name1 %></p><p><%= obj.group_name2 %></p></td>
          <td><p><%= f.text_field :vCenter_Version,:size=>"15" %></p><p><%= f.text_field :Esxi_Version,:size=>"15" %></p></td>
          <td><p><%= obj.vcenter_compliant %></p><p><%= obj.esxi_compliant %></p></td>
          <td><p><%= obj.vcenter_non_compliant %></p><p><%= obj.esxi_non_compliant %></p></td>
          <td><p><%= obj.vcenter_total %></p><p><%= obj.esxi_total %></p></td>
          <td><%= f.submit 'Check Compliance', :onclick =>"this.setAttribute('style', 'pointer-events:none;opacity:0.4')"%></td>
          <td><%= f.submit 'Generate', :onclick =>"this.setAttribute('style', 'pointer-events:none;opacity:0.4')"%></td>
          <td><%= obj.updated_at %></td>
          <%end%>
        </tr>
  <% end %>
  </tbody>
</table>

app/views/sungard/compliance_compute/new.html.erb
<% @requirejs_options = {
  'config' => {
    'application' => {
      'disableRouter' => true
    }
  }
}
%>
<% content_for :requirejs do %>

  require(['application'], function(app){
  })

<% end %>
<div class="dialog_form">
  <%= render 'form' %>
</div>