config/routes.rb
Viewpoint::Application.routes.draw do



  ############################# VP5 Proxy Routing ###################################
  #Common Portal Landing page internal and external users proxy through home controller
  match '/my_board', to: 'welcome#landing_page', :as => :my_board, via: [:get]
  match '/my_tutorials', to: 'welcome#tutorials_page', :as => :my_tutorials, via: [:get]
  #For DNS-IPAM release(6.15.0) we will remove old DNS link and always redirect user to new DNS/IPAM pages
  # match "/dns" => redirect("/ui/index.html#/dns"), :as => :dns
  match '/dns', to: 'welcome#dns_page', :as => :vp_dns, via: [:get]
  # redirect old vpp4 reports to new vp5 reports
  # match "/reports" => redirect("/ui/index.html#/reports"), :as => :reports
  match "/reports", to: 'welcome#reports_page', :as => :reports, via: [:get]
  match "/restricted_contracts", to: 'welcome#restricted_contracts', :as => :restricted_contracts, via: [:get]
  match "/restricted_invoices", to: 'welcome#restricted_invoices', :as => :restricted_invoices, via: [:get]
  match "/ipam", to: 'welcome#ipam', :as => :ipam, via: [:get]
  match "/patching_schedule", to: 'welcome#patching_schedule', :as => :patching_schedule, via: [:get]
  match "/patching_policy", to: 'welcome#patching_policy', :as => :patching_policy, via: [:get]
  match "/patching_servers", to: 'welcome#patching_servers', :as => :patching_servers, via: [:get]
  match "/sg_cloud_portal", to: 'welcome#sg_cloud_portal', :as => :sg_cloud_portal, via: [:get]
  match "/vp_firewalls", to: 'welcome#vp_firewalls', :as => :vp_firewalls, via: [:get]
  match "/ipv4", to: 'welcome#ipv4', :as => :ipv4, via: [:get]
  match "/ipv6", to: 'welcome#ipv6', :as => :ipv6, via: [:get]
  match "/company_dns_audits", to: 'welcome#dns_audits', :as => :dns_audits, via: [:get]
  match "/hpc_admin", to: 'welcome#hpc_admin', :as => :hpc_admin, via: [:get]
  match "/command_runner/:asset_guid", to: 'welcome#command_runner', :as => :command_runner, via: [:get]
  match "/osappdashboard", to: 'welcome#osappdashboard', :as => :osappdashboard, via: [:get]
  match "/pyxie_reports/:folder", to: 'welcome#pyxie_reports', :as => :pyxie_reports, via: [:get]

  resources :interfaces
  resources :reports do
    collection do
      get '/notifications' => 'reports#notifications'
    end
  end
  resources :searches
  resources :events
  resources :histories
  resources :groups
  resources :masquerades
  resources :company_masquerades
  resources :event_subscriptions
  resources :helps
  resources :graphs
  resources :dashboards
  resources :ticketing
  resource :oid

  resources :reqs do
    collection do
      get 'group'
      get 'device_sysedge'
      get 'device_server'
      get 'area'
      get 'cabinet'
    end
  end

  match 'auth/:provider/callback', to: 'oids#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  # match 'auth/viewpoint', to: 'oids#create', via: [:get, :post]

  scope path: '/api', defaults: {format: 'json'}, as: :api do
    scope :module => 'api/v1', constraints: SGTools::Rails::REST.api_constraints_class.new(version: 1, default: true)  do

      # Below are the test api routes for testing performance
      get '/ehealth/test_ticketing_incidents' => "ehealth#test_ticketing_incidents"
      get '/ehealth/test_ticketing_requests' => "ehealth#test_ticketing_requests"
      get '/ehealth/test_ticketing_change_requests' => "ehealth#test_ticketing_change_requests"
      get '/ehealth/test_ticketing_maintenance' => "ehealth#test_ticketing_maintenance"
      get '/ehealth/test_events' => "ehealth#test_events"
      get '/ehealth/:asset_guid/test_active_asset_status' => "ehealth#test_active_asset_status"
      get '/ehealth/:asset_guid/test_active_asset_incidents' => "ehealth#test_active_asset_incidents"
      get '/ehealth/:asset_guid/test_active_asset_req_changes' => "ehealth#test_active_asset_req_changes"
      get '/ehealth/:asset_guid/test_active_asset_mx_windows' => "ehealth#test_active_asset_mx_windows"
      get '/ehealth/:company_guid/test_active_assets' => "ehealth#test_active_assets"

      get '/ehealth/events' => "ehealth#events"
      get '/ehealth/backups' => "ehealth#backups"
      get '/ehealth/backups_for_month' => "ehealth#backups_for_month"
      get '/ehealth/backup_months' => "ehealth#backup_months"
      get '/ehealth/environment_healths' => "ehealth#environment_healths"
      get '/ehealth/groups_environment_health' => "ehealth#groups_environment_health"
      get '/ehealth/asset_types' => "ehealth#asset_types"
      get '/ehealth/:asset_type/active_assets_by_type' => "ehealth#active_assets_by_type"
      get '/ehealth/active_assets' => "ehealth#active_assets"
      get '/ehealth/:group_id/group_active_assets' => "ehealth#group_active_assets"
      get '/ehealth/ticketings' => "ehealth#ticketings"
      get "/group_glances", to: "group_glances#index"
      get "/vp/devices", to: "generic_devices#index"
      get "/recent_assets", to: "recent_assets#index"

      get '/ticket_landing/ticket_stats' => "ticket_landing#ticket_stats"
      get '/ticket_landing/asset_health' => "ticket_landing#asset_health"
      get '/ticket_landing/recent_assets' => "ticket_landing#recent_assets"
      get '/ticket_landing/tickets' => "ticket_landing#tickets"
      get '/ticket_landing/asset_health' => "ticket_landing#asset_health"
      get '/ticket_landing/groups_health' => "ticket_landing#groups_health"
      get '/ticket_landing/sn_user_roles' => "ticket_landing#sn_user_roles"

      get "/device_command/:asset_guid", to: "commands#device_command"
      get "/device_search", to: "searches#device_search"

      get "/device_command/:asset_guid", to: "commands#device_command"
      get '/device_objects/:asset_guid', to: 'commands#device_objects'
      get '/device_object_groups/:asset_guid', to: 'commands#device_object_groups'
      get '/device_groups/:asset_guid', to: 'commands#device_groups'
      get '/device_services/:asset_guid', to: 'commands#device_services'
      get "/delete_user",to: "vp_users#delete_user"
      get "/device_search", to: "searches#device_search"

      get "/device_reports", to: "device_reports#index"
      get "/network_interface_subscriptions", to: "device_reports#network_interface"
      get "/device_availability_subscriptions", to: "device_reports#device_availability"

      get "firewalls/archive", to: "firewalls#archive"
      get "/vp_devices/by_ip", to: "vp_devices#by_ip"

      resources :company_subscriptions
      resources :device_subscriptions
      resources :internet_usages
      resources :groups
      resources :devices
      resources :device_glances
      resources :group_availabilities
      resources :power_reports
      resources :event_subscriptions
      resources :msa_subscriptions do
        collection do
          get 'company_device_availability_pdf'
          get 'company_device_availability_csv'
          get 'company_network_availability_pdf'
          get 'company_network_availability_csv'
          get 'company_power_availability_pdf'
          get 'company_power_availability_csv'
          get 'company_availability_pdf'
          get 'network_path_performance_pdf'
          get 'company_availability_csv'
          get 'group_availability'
          get 'network_path_performance_csv'
        end
      end
      resources :openid, constraints: {id: /.+/} # allow for email as param
      resources :vp_devices
      resources :vp_interfaces
      resources :current_users
      resources :foos
      resources :bars
      resources :reqs, only: [:index,:create,:destroy] do
        collection do
          put 'ack'
          get 'subscriptions'
        end
      end
      resources :statements do
        collection do
          get 'groups'
          get 'device_sysedge'
          get 'device_server'
          get 'areas'
          get 'cabinets'
        end
      end

      resources :event_subscriptions do
        collection do
          match '/event_subscriptions' => 'event_subscriptions#index', via: [:get]
        end
      end

      resources :locations do
        collection do
          match '/locations' => 'locations#index', via: [:get, :post]
        end
      end

      get "/vp/devices", to: "generic_devices#index"

      ########## Viewpoint API for Unified Portal ##################
      namespace :portal do
        get "/masquerades",to: "masquerades#index"
        get "/masquerades/:company_guid", to: "masquerades#show"
        get "/masquerades/new/:id",to: "masquerades#new"
        get "/unmasquerade", to: "masquerades#destroy"

        get "/switch_companies",to: "company_masquerades#index"
        get "/switch_company/new/:id",to: "company_masquerades#new"
        get '/home_company', to: 'company_masquerades#destroy', as: 'home_company'
        get '/search/:collection', to: "search#search"
        get '/tool_selectors', to: "tool_selectors#index"
        get '/portal_selectors', to: "portal_selectors#index"
        get '/quick_links', to: "tool_selectors#quick_links"

        get "forgot_password/:user_guid", to: "users#forgot_password"
        get "country_codes", to: "users#country_codes"
        get "timezones", to: "users#timezones"
        get "sn_permissions", to: "users#sn_permissions"

        post 'request_logger',to: "request_logger#index"

        scope '/mock' do
          get 'vp_tools_selector', to: 'mock#vp_tools_selector'
          get 'raas_tools_selector', to: 'mock#raas_tools_selector'
          get 'get_info_html', to: 'mock#get_info_html'
          get 'help_sections', to: 'mock#help_sections'
          get 'get_compliance_status', to: 'mock#compliance_status'

app/models/report.rb
class Report

  def self.all_reports_list(company_guid)   
    report_dir = Viewpoint::Application::USAGE_REPORTS + company_guid
    report_dir = report_dir.downcase
    Rails.logger.info("the report dir: #{report_dir}")
    if File.directory?(report_dir)
      Dir.chdir(report_dir) 
      arr = Array.new
      i = 0
      farr = Dir.glob('*.*')
      farr.each do |file| 
        # ignore the fo type files
        if File.extname(file) != '.fo'
          if File.extname(file) == '.pdf'
            e = "pdf"
          end
          if File.extname(file) == '.txt'
            e = "txt"
          end
          if File.extname(file) == '.csv'
            e = "csv"
          end
          arr[i] = Hash.new
          arr[i] = {name: File.basename(file), type: get_report_type(file), date: File.mtime(file), ext: e}
          i += 1
        end  
      end
      arr
    else
      # report directory does not exist for this company
      # returning an empty array so the page renders, grid will be empty
      arr = []
    end
  end

  def self.construct_path(file_name, company_guid, file_extension_type)
    report_dir = Viewpoint::Application::USAGE_REPORTS + company_guid
    report_dir = report_dir.downcase
    f = report_dir + "/" + file_name + "." + file_extension_type
  end 

  def self.get_report_type(f)
    if (f =~ /power(.*)/ )
      r = "powerbar"
    end
    if (f =~ /usage(.*)/ )
      r = "usage"
    end
    if (f =~ /vpls(.*)/ )
      r = "vpls"
    end
    if (f =~ /internet(.*)/ )
      r = "internet"
    end
    r
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  # generated reports displayed on the index page
  # for testing power report drop downs use "The McGraw-Hill Companies Ltd"
  before_filter :set_body_class
  before_filter lambda { help_menu_name('reports') }
  
  def index
    @body_class = "reports single-column"
    #
    # TODO: this list must now be populated from the pyxie API calls
    # TODO: the index page should show the file as a clickable item
    #
    # http://localhost:3006/pyxie - available buckets by current user
    # http://localhost:3006/pyxie/suba_ehealth - all files for a bucket
    #  
    @reports = Report.all_reports_list(current_user.company_guid)    
    # required for form display
    @form_type = "new"
    @req = Req.new
    @group_dat = Group.dat_for_dropdown(current_user.company_guid)
    @device_dat = Device.dat_for_dropdown(current_user.asset_list)
    @device_sysedge = Device.dropdown_by_device_class(current_user.asset_list,"SysEdge")
    @device_server = Device.dropdown_by_device_class(current_user.asset_list,"Server")

    # hidden form fields 
    @current_user_email = current_user.email
    @current_user_company_guid = current_user.company_guid
    @current_user_guid = current_user.guid

    @area_dat = Power.find_distinct_area(current_user.company_guid)
    @cabinet_dat = Power.find_distinct_cabinet(current_user.company_guid)    
    respond_to do |format|
      format.html
    end
  end

  def notifications
    @body_class = "reports single-column"
    @notification_tools = "reports single-column"
  end

  # TODO: based on the new functionality in pyxie, this method can be removed
  # the file should be clickable in the index grid
  def show
    company_guid = current_user.company_guid
    report_name = params[:id]  
    report_format = params[:ext]  
    f = Report.construct_path(report_name, company_guid, report_format)
    if params[:format] == "txt"
      send_file f, :type => "application/txt", :x_sendfile => true
    else  
      send_file f, :type => "application/pdf", :x_sendfile => true
    end
  end

  private

  def set_body_class
    add_body_class "reports single-column"
  end

  def add_body_class(new_class)
    @body_class ||= ""
    @body_class << "#{new_class}"
  end

end

app/views/reports/_form.html.erb
<div class="error_messages" style="display:none;"><p class="success"></p></div>
<div id="custom_report">
  <%= form_for(@req) do |f| %>
  <% if @form_type == "new" %>
    <input type="hidden" id="req_report_name" name="report_name" value="Health Report / Device Detail"/>
    <!-- form for new -->
    <ul class="form_list">
      <li>
        <%= f.label :report_id, "Report" %>
        <%= f.collection_select :report_id, Req.new_report_id, :first, :last %>
      </li>

      <li class="setg">
        <%= f.check_box :show_graphs,{:checked=>true} %> show graphs
      </li>

      <li class="set">
        <%= f.label :report_type, "Report Type" %>
        <%= f.collection_select :report_type, report_type, :first, :last %>
      </li>

      <!-- "Health..."" and "Raw Polled..." -->
      <li class="radio_group set0">
        <label><input type="radio" name="report_subject" class="report_subject group" value="group" /> Group</label>
        <label><input type="radio" name="report_subject" class="report_subject device" value="device" /> Device</label>
      </li>
      <li id="report_subjects" class="set1"> 
        <div class="set1a">
        <%= f.collection_select :group_guid, {}, :id,:name, 
          {:include_blank => 'Select Group'}, {:class => 'group'} %>
        </div>
        <div class="set1b">
        <%= f.collection_select :device_guid, {}, :asset_guid,:name,  
          {:include_blank => "Select Device"}, {:class => "device"} %>
        </div>
      </li>

      <li class="set3">
        <%= f.label :area %>
        <%= f.select :area, {}, 
          {:include_blank => 'Select Area'} %>
      </li>
      <li class="set3">
        <%= f.label :cabinet, "Cabinet" %>
        <%= f.select :cabinet, {}, 
          {:include_blank => 'Select Cabinet'} %>
      </li>
      <% if APP_CONFIG['bus_report_process'] %>
      <% end %>
    </ul>
    <ul class="form_cal">
      <li>
        <%= f.label :start_date, "Start Date" %>
        <%= f.text_field :start_date %>
        <div id="start_date_div"></div>
      </li>
      <li>
        <%= f.label :end_date, "End Date" %>
        <%= f.text_field :end_date %>
        <div id="end_date_div"></div>
      </li>
    </ul>
  <!-- /end form for new -->
  <% end %>

  <!-- Schedular -->
  <ul class="scheduler">
   <li>
      <label for="req_subscription">
        <%= f.check_box :subscription %>Schedule this for periodic delivery.
      </label>
    </li>
    <li class="set4">
      <%= f.label :frequency, "Frequency" %>
      <%= f.collection_select :frequency, frequency_range, :first, :last, 
        {:include_blank => 'Select Frequency'} %>
    </li>
    <li class="set4">
      <label>Time</label>
      <%= f.collection_select :delivery_time, time_range, :first, :last, 
        {:include_blank => 'Select Time'} %>
    </li>
    <li class="set4">
      <label>Time Zone</label>
       <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all %>
    </li>
    <li class="set4 email">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, :value => @current_user_email %>
      <%= f.hidden_field :company_guid, :value => @current_user_company_guid %>
      <%= f.hidden_field :user_guid, :value => @current_user_guid %>
    </li>
  </ul>
  <!-- end scheduler -->

  <div class="form_submit">
    <!-- <a>close</a> -->
    <%= submit_tag "Submit" %>
    <div id="wait_progress">
      <div id="please_wait"></div>
      <div class="progress-bar blue stripes">
        <span style="width: 100%"></span>
      </div>
    </div>
  </div>
  
<% end %>

</div>

app/views/reports/_tools.html.erb
<% if @notification_tools %>

<h2>Notifications</h2>

<% else %>

<h2 class="button" id="bucket_select">
  <div class="expand"><b class="here reports">browse reports</b>
    <ul>
    </ul>
  </div>
</h2>
<h2></h2>
<%= link_to "custom report", new_req_path ,:class => 'button add'%>

<% end %>

app/views/reports/index.html.erb
<% @requirejs_options = {
  'config' => {
    'application' => {
      'disableRouter' => true
    }
  }
}
%>

<% content_for :requirejs do %>

  require(['application'], function(app){
  app.module('reports').start();
  })

<% end %>

<table id="reports" class="grid delay_apply_datatable">
  <thead>  
    <tr>
      <th class="bucket_name"></th>
      <th>File Size</th>
      <th class="default_sort">Date</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td colspan="100"><div style="padding: 1em; text-align: center;">Select a report type from the "browse reports" pull down.</div></td>
      </tr>
  </tbody>
</table>

app/views/reports/notifications.html.erb
<% @requirejs_options = {
  'config' => {
    'application' => {
      'disableRouter' => true
    }
  }
}
%>

<% content_for :requirejs do %>

  require(['application'], function(app){
  app.module('reports').start();
  })

<% end %>

<table id="noti_table" class="grid delay_apply_datatable show_all">
  <thead>  
    <tr>
      <th>Notification</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td colspan="100"><div class="loading"><div class="image"></div></div></td>
      </tr>
  </tbody>
</table>